---
title: Wax
timezone: UTC
collections:
  exhibits:
    title: Exhibits
    output: true
  posts:
    title: Posts
    output: true
  qatar:
    title: Qatar
    output: true
    layout: qatar_item
    metadata:
      source: qatar.csv
    images:
      source: raw_images/qatar
  uploads:
    title: Uploads
    output: true
description: Minimal Exhibitions with Jekyll
url: https://minicomp.github.io
baseurl: "/wax"
copyright: Example copyright org, 2019
logo: "/assets/logo.png"
permalink: pretty
sass:
  style: compressed
exclude:
- Gemfile*
- Rakefile
- vendor
- spec
- README.md
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
search:
  main:
    index: "/search/index.json"
    collections:
      qatar:
        content: false
        fields:
        - artist
        - location
        - label
        - _date
        - object_type
        - current_location
menu:
- label: About
  sub:
  - label: Wax
    link: "/about/"
  - label: Documentation
    link: https://minicomp.github.io/wiki/wax/
  - label: Credits
    link: "/credits/"
- label: Exhibits
  sub:
  - label: Inline Parallax Image
    link: "/exhibits/a/"
  - label: Inline Image References
    link: "/exhibits/b/"
- label: Browse
  link: "/collection/"
- label: Search
  link: "/search/"
- label: Reuse
  link: "/reuse/"
footer:
  links:
  - label: GitHub
    link: https://github.com/minicomp/wax
  - label: Credits
    link: "/credits"
  - label: Contact
    link: https://gitter.im/minicomp/wax/
  logos:
  - img: "/img/logo.png"
